version: '3.3'

services:
  apiclient:
    image: toto_api_client:0.0.5
    build: "."
    ports:
      - "7171"
    restart: "always"
    networks:
      - "totoapiclient.network"
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 5s
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apiclient
    ports:
      - "7071:7071"
    restart: always
    networks:
      - "totoapiclient.network"
networks:
  totoapiclient.network: