### GET
POST http://localhost:9000/api/servicetoken
Content-Type: application/json

{
    "token" : "qC5Ym%2BBvXzabGp34jJlKvnC6wCrr3pLCwBzsLoSzl4k%3D"
}

### INIT
POST http://localhost:9000/api/serviceinit
Content-Type: application/json

{
    "member_company" : "MMD"
}

### CHECK PASARAN
POST http://localhost:9000/api/servicecheckpasaran
Content-Type: application/json

{
    "member_company" : "MMD",
    "pasaran_code" : "CAM"
}

### RESULT
POST http://localhost:9000/api/serviceresult
Content-Type: application/json

{
    "member_company" : "MMD",
    "pasaran_code" : "CAM"
}


### SERVICE CONFIGTOGEL
POST http://localhost:9000/service/serviceconfigtogel
Content-Type: application/json

{
    "member_company" : "MMD",
    "pasaran_code" : "SG",
    "permainan" : "shio"
}

### SERVICE LIMITTOGEL
POST http://localhost:9000/service/servicelimittogel
Content-Type: application/json

{
    "member_company" : "MMD",
    "member_username" : "developer",
    "pasaran_code" : "SG",
    "pasaran_periode" : "4",
    "tipe_game" : "4-3-2"
}

### SERVICE SAVE TRANSAKSI
POST http://localhost:9000/service/servicesavetransaksi
Content-Type: application/json

{
    "member_username" : "developer",
    "member_company" : "MMD",
    "idtrxkeluaran" : "212198",
    "idcomppasaran" : "191",
    "devicemember" : "MOBILE",
    "formipaddress" : "192.0.0.1",
    "totalbayarbet" : 150000,
    "list4d" : [
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "1500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "2500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "3500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "4500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "5500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "6500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "7500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "8500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "9500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "600", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0"}
    ]
}


### SERVICE LIVE TRANSAKSI
POST http://128.199.171.22/service/servicesavetransaksi
Content-Type: application/json

{
    "member_username" : "developer",
    "member_company" : "MMD",
    "idtrxkeluaran" : "212198",
    "idcomppasaran" : "191",
    "devicemember" : "MOBILE",
    "formipaddress" : "192.0.0.1",
    "totalbayarbet" : 150000,
    "list4d" : [
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "1500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "2500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "3500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "4500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "5500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "6500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "7500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "8500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "9500", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"},
        {"id": "2552", "nomor": "99", "permainan": "2DD", "bet": "600", "diskon": "145", "diskonpercen": "0.29", "bayar": "355", "kei":"0" ,"kei_percen":"0", "win":"20"}
    ]
}