const Madmin = require('./Madmin')
const Mcounter = require('./Mcounter')
const Mpasaran = require('./Mpasaran')
const Mpasaranoffline = require('./Mpasaranoffline')
const Mkeluaran = require('./Mkeluaran')
const Mkeluarandetail = require('./Mkeluarandetail')
const Mcompanypasaran = require('./Mcompanypasaran')
const Minvoice = require('./Minvoice')
const model = {}

model.Madmin = Madmin
model.Mcounter = Mcounter
model.Mpasaran = Mpasaran
model.Mpasaranoffline = Mpasaranoffline
model.Mkeluaran = Mkeluaran
model.Mkeluarandetail = Mkeluarandetail
model.Mcompanypasaran = Mcompanypasaran
model.Minvoice = Minvoice
module.exports = model